title: Default Page

status:
  draft:
    label: Brouillon
    text: La page est en cours de rédaction.
  listed:
    label: Publiée
    text: La page est visible publiquement.

options:
  preview: "http://localhost:3001/{{ page.slug }}"

fields:
  contenu:
    label: Contenu
    type: blocks
    fieldsets:
      - textWithTitle
      - location
      - type: location
        name: Localisation google maps
        icon: map
      - type: film-list
        name: Liste de films
        icon: video
        preview: fields
        wysiwyg: true
        fields:
          category:
            label: Catégorie
            type: select
            required: true
            options:
              all: Tous les films
              kids: Film pour enfant
              senior: 65+
            default: all
